Doxygen: OAException Class Reference
OAException Class Reference
#include <ObjectAllocator.h>
Public Types
enum OA_EXCEPTION {
E_NO_MEMORY, E_NO_PAGES, E_BAD_BOUNDARY, E_MULTIPLE_FREE,
E_CORRUPTED_BLOCK
}
Public Member Functions
OAException (OA_EXCEPTION ErrCode, const std::string &Message)
virtual ~OAException ()
OA_EXCEPTION code () const
virtual const char * what () const
Private Attributes
OA_EXCEPTION error_code_
The error code (one of the 5)
std::string message_
The formatted string for the user.
Detailed Description
Exception class
Definition at line 29 of file ObjectAllocator.h.
Member Enumeration Documentation
OA_EXCEPTION
enum OAException::OA_EXCEPTION
Possible exception codes
Enumerator
E_NO_MEMORY
out of physical memory (operator new fails)
E_NO_PAGES
out of logical memory (max pages has been reached)
E_BAD_BOUNDARY
block address is on a page, but not on any block-boundary
E_MULTIPLE_FREE
block has already been freed
E_CORRUPTED_BLOCK
block has been corrupted (pad bytes have been overwritten)
Definition at line 35 of file ObjectAllocator.h.
     {
       E_NO_MEMORY,
       E_NO_PAGES,
       E_BAD_BOUNDARY,
       E_MULTIPLE_FREE,
       E_CORRUPTED_BLOCK
     };
Constructor & Destructor Documentation
OAException()
OAException::OAException (OA_EXCEPTION ErrCode, const std::string & Message) inline
Constructor
Parameters
ErrCode One of the 5 error codes listed above
Message A message returned by the what method.
Definition at line 53 of file ObjectAllocator.h.
 : error_code_(ErrCode), message_(Message) {};
~OAException()
virtual OAException::~OAException () inline virtual
Destructor
Definition at line 58 of file ObjectAllocator.h.
{
     }
Member Function Documentation
code()
OA_EXCEPTION OAException::code () const inline
Retrieves the error code
Returns
One of the 5 error codes.
Definition at line 67 of file ObjectAllocator.h.
{
       return error_code_;
     }
References error_code_.
Referenced by TestCorruption(), and TestValidate().
what()
virtual const char* OAException::what () const inline virtual
Retrieves a human-readable string regarding the error.
Returns
The NUL-terminated string representing the error.
Definition at line 77 of file ObjectAllocator.h.
{
       return message_.c_str();
     }
References message_.
Referenced by DisableOA(), DoEmployees(), DoStudents(), Stress(), StressFreeChecking(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestLeak(), and TestValidate().
Member Data Documentation
error_code_
OA_EXCEPTION OAException::error_code_ private
The error code (one of the 5)
Definition at line 81 of file ObjectAllocator.h.
Referenced by code().
message_
std::string OAException::message_ private
The formatted string for the user.
Definition at line 82 of file ObjectAllocator.h.
Referenced by what().
The documentation for this class was generated from the following file:
ObjectAllocator.h